version: "3"
services:
  api:
    image: webtruyenchu_backend
    build: .
#      context: .
#      dockerfile: WebTruyenChu_Backend/Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:5001;http://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin@123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - webtruyenchudata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
    ports:
      - "1433:1433"
volumes:
    webtruyenchudata:
      external: true 